### ISSUE TITLE
Remove/replace misleading example for custom close reasons

### ISSUE THREAD

**Issue by codygray** [SO-Close-Vote-Reviewers/socvr-website-content#25]
In the [What Should Request Reasons Contain?](https://socvr.org/faq#what-should-request-reasons-contain) section of the FAQ, it says the following:

> For `cv-pls` requests: As with most requests, a request reason is required. **It is *highly recommended* that your request reason includes your actual close reason**, even if that was a custom reason (e.g. "Custom: Homework without attempt"). Including an actual close reason significantly increases the likelihood that your request will be acted upon by other users. A request reason of just "off-topic" is insufficient, because it leaves too many possibilities as to why you feel the question should be closed.

This is great advice, but the example is bad. "Homework without attempt" is **not** a valid close reason, and therefore should not be given in the official FAQ as an example. This example should either be replaced or removed (if we cannot agree on a suitable replacement).

As a replacement, consider: "Custom: SEO question unrelated to programming" or "Custom: customer support request for a third-party service".

**This needs to happen sooner, rather than later!**

**Comment by codygray** [comment]
That's...not really fair, and wholly unrelated to the nature of this request, which doesn't cite the Help Center as a justification in any form or fashion.

**Comment by makyen** [comment]
Note: I've moved this to the website content repository, because this appears to be an issue about the content of the SOCVR website, rather than something that's intended as a topic for a SOCVR room meeting.

**Comment by Tiny-Giant** [comment]
I know I haven't been a part of the community for approximately a year now, but I had to chime in to agree with Cody here. 

A homework question is essentially a how to question that someone has determined was given to the asker as homework. The homework adjective is therefor contextual and not material to the question itself. 

How to questions do not, and have not ever, required an attempt to solve the problem, nor do they actually benefit from such an attempt. Providing an attempt turns the question into a debugging question rather than a how to question  which artificially limits the scope of answers the question is likely to receive, which is a true detriment to the community at large, especially future readers who don't care about the failed attempt or how to fix it, but are rather looking for the various ways that experienced programmers would attempt the task and the pros and cons of each method provided. 

Largely how to questions that are shoehorned into debugging questions by overzealous reviewers are useless to future viewers unless somehow that viewer has attempted to do the same thing the same way and made the same mistake, but again the usefulness of such a question answer pair are likely to be drastically lower than a question simply asking (with reasonable scope) how to perform a task and the list of answers provided.

**Comment by Tiny-Giant** [comment]
I decided to put this in another comment because it is tangential to my previous comment: as someone who primarily views the site as a future viewer at this point, it is extremely frustrating to arrive at a question asking how to solve a narrowly scoped problem from Google that is exactly the problem I need to solve, only to find it closed because people deemed it to be a homework problem and no attempt was provided. I didn't get assigned the problem for homework, I got it *at work* and just want to know the solution(s) that people more experienced than me with the technology at hand would come up with to solve said problem.

**Comment by codygray** [comment]
I miss your insight and agreement with me, @Tiny-Giant... I hope you are doing well through these trying times.

I posted this as a topic for a room owners' meeting because I was afraid it might be "controversial", for reasons unknown to me, and therefore require discussion before we could just make the change. (And also partly because I was not aware of this other repository.)

Putting aside whether I agree or disagree that homework is a valid reason to close a question under the current rules, I just don't think it's a good example because (A) there is disagreement, and (B) there are many subtleties to assessing the topicality of homework questions, even under TylerH's interpretation.

**Comment by Tiny-Giant** [comment]
Thanks for your kind words @codygray.

I believe that your assertion is reasonable that because there is disagreement about the topicality of "homework" questions sans attempt, it should not be used as an example of a reasonable custom close reason. Such an example should be commonly agreed upon and should not be controversial.

I'm certain that a more suitable example could be found, for instance the SEO reason proposed by Cody that was, in my experience, a commonly used custom reason when I was last active.

**Comment by Tyler-H** [comment]
@Tiny-Giant For what it's worth, I sympathize and agree with you that some questions get improperly closed for that reason. For example, I don't think it's appropriate for readers to assume a question is homework unless the user states that, either implicitly ("I have a homework assignment that says: ...") or explicitly (in response to a question). Just because something *smells* like homework doesn't mean it is... a lot of people ask basic, homework-esque questions when trying to learn or work their way through coding challenges/puzzles.

I also believe, generally, in allowing users to edit the question to include an attempt first (you know, that whole 'good faith' thing). I've criticized users in chat before for posting cv-pls requests less than a minute after the question was posted, and/or when they didn't comment to suggest to OP that they need to include an MCVE, for example, because I know it's much harder to reopen a question than close one in the first place.

That being said, frustration that someone else had the same question as you and it didn't get an answer is not the problem of SOCVR, or the site. There's *clear* precedence that that expectation has been in place for a while. I understand Cody's and your *personal* frustration with that being a policy, but it's just that: a personal view. it's just not the place to have such a debate. If Meta consensus changes or a mandate from the company arrives that dictates a different position in this, I'll be happy to enforce it in SOCVR. Until then, *them's the rules*.

**Comment by Tiny-Giant** [comment]
@Tyler-H I can't tell if you're purposefully being obtuse, or you just didn't read my main argument at all and instead chose to respond to the comment that I explicitly stated was tangential to the main discussion. I will repeat / rephrase my main arguments below and refrain from adding any excess tangential remarks that may cause you to completely ignore my argument.

Your assertion that any how to question whatsoever has at any point required any semblance of an attempt is completely and provably false. The idea that any how to question should require an attempt is directly counter to the goal of building a repository of solutions to reasonably scoped, on-topic programming problems. 

Stack Overflow is not a mentoring site as you seem to think it is. Stack Overflow does not exist to teach people how to learn how to code. Requiring the people that are providing the problem to solve it themselves does not advance the goal of building a repository of solutions to reasonably scoped, on-topic programming problems. Doing so directly discourages answerers from providing answers that would solve the problem in a manner other than that attempted by the person posing the problem (that person also most likely being the least experienced with the technology at hand, and therefor the least likely to be able to come up with even a good attempt at a solution), and you will encourage answerers to provide answers that are of precisely zero use to future viewers.

Questions and answers exist for the tens or hundreds of thousands of future viewers that will consume the question and it's answers, not for the asker that will view the question once and never return. We should strive to curate the content on the site such that it is the most useful for the users who will actually be making the most use of the content, instead of attempting to make the content as useless as humanly possible for as many people as we can.

In response to your quote from the help center: that quote has been disputed since the day it was added to the help center, and as far as I can tell **it only still exists solely to confuse askers and people voting to close questions**.

**Regardless**. Even if you choose to ignore logic and reason and to use your own interpretation of an ambiguous quote from the help center that a large portion of the community disagrees with as gospel, given that a large portion of the community disagrees with your interpretation, it should not be used as an example of a commonly agreed upon reasonable custom close reason. That is a misrepresentation of community's lack of agreement on the matter at best, and at worst it is complete disregard for the entire portion of the community that disagrees with you, as if your opinion is more valuable than literally everyone else's. 

Regardless of whether such request are allowed or disallowed in the SOCVR, topicality of such questions is disputed at best and therefor should the reason should be precluded from being used as an example in that text in favor of a custom close reason that is not disputed, **such as the SEO example provided by @codygray**. As far as I know, the SEO example is not disputed by anyone at all, it is a commonly agreed upon reasonable use of a custom close reason, and therefor **it would make a much better example**.
